---
version: "3.1"

services:

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=example
    ports:
      - 5432:5432

  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - 3306:3306

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  es:
    image: elasticsearch:7.9.0
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
