# The URL the site will be built for
base_url = "https://mitre-migrations.io"
compile_sass = false
build_search_index = true
languages = [
    {code = "de"}
]

[markdown]
highlight_code = true

[extra]