---
name: Rust Project Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
      - uses: Swatinem/rust-cache@v1
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose

    services:
      mariadb:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: example
        ports:
          - 3306:3306
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: example
        ports:
          - 5432:5432
