name: Rust Project Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run cargo-deny
      run: cargo deny check

    services:
      mariadb:
        image: mariadb:latest
        env:
          - MYSQL_ROOT_PASSWORD=example
        ports:
          - 3306:3306